version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 100
  groups:
    awssdk:
      patterns:
        - "AWSSDK*"
    azure:
      patterns:
        - "Azure*"
    hangfire:
      patterns:
        - "Hangfire*"
    nlog:
      patterns:
        - "NLog*"
    aspire:
      patterns:
        - "Aspire*"
    core:
      patterns:
        - "Microsoft*"
        - "Npgsql*"
        - "Swashbuckle*"
        - "Autofac*"
        - "System*"
        - "Newtonsoft*"
  
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 100
  reviewers:
  - berviantoleo
  assignees:
  - berviantoleo

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 100
  reviewers:
  - berviantoleo
  assignees:
  - berviantoleo
